create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text not null,
  excerpt text,
  content text,
  cover_url text,
  author text default 'Vietnam Sports Daily',
  status text default 'draft',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.articles enable row level security;

create policy "public can read published articles"
on public.articles for select
using (status = 'published');

create policy "authenticated users can manage articles"
on public.articles for all
to authenticated
using (true)
with check (true);